-- Shared core: household root + membership + invites + RLS helpers.
--
-- These tables live in `public.*` (Supabase's default PostgREST-exposed
-- schema) so a future second app in this Supabase project (planned: a
-- habit-tracker that will eventually merge with Hearth) can FK to
-- public.households and share authentication without a schema rewrite.
--
-- Hearth-specific tables go in the `hearth` schema in the next migration.

set check_function_bodies = off;
create extension if not exists "pgcrypto";  -- gen_random_uuid()

-- ============================================================================
-- Households (tenant root)
-- ============================================================================
create table if not exists public.households (
    id          uuid primary key default gen_random_uuid(),
    name        text not null,
    created_at  timestamptz default now(),
    updated_at  timestamptz default now()
);

-- ============================================================================
-- Household membership
--   * One user belongs to at most one household in v1 (UNIQUE(user_id)).
--     Drop the UNIQUE later to enable multi-membership without a migration
--     of the join table itself.
--   * Role is owner/member; CHECK enforces the enum.
--   * locale lives on the membership row (not the user) because it's a
--     per-household preference (a Swedish user joining an English-speaking
--     household may want the app in English).
-- ============================================================================
create table if not exists public.household_members (
    household_id  uuid not null references public.households(id) on delete cascade,
    user_id       uuid not null references auth.users(id)        on delete cascade,
    role          text not null default 'member' check (role in ('owner', 'member')),
    locale        text not null default 'en'     check (locale in ('en', 'sv')),
    joined_at     timestamptz default now(),
    primary key (household_id, user_id),
    unique (user_id)
);
create index if not exists idx_household_members_user
    on public.household_members (user_id);

-- At most one owner per household.
create unique index if not exists idx_one_owner_per_household
    on public.household_members (household_id)
    where role = 'owner';

-- ============================================================================
-- Invite tokens
--   * Cryptographically-random opaque tokens generated by FastAPI (the
--     server picks a 32-byte URL-safe random; we store it as text).
--   * 7-day default expiry (set by the inserting endpoint, not the schema).
--   * Consumed in a service-role transaction: validate -> mark used ->
--     insert into household_members.
-- ============================================================================
create table if not exists public.household_invites (
    token         text primary key,
    household_id  uuid not null references public.households(id) on delete cascade,
    created_by    uuid not null references auth.users(id)        on delete cascade,
    expires_at    timestamptz not null,
    used_at       timestamptz,
    used_by       uuid references auth.users(id),
    created_at    timestamptz default now()
);
create index if not exists idx_household_invites_household
    on public.household_invites (household_id);
create index if not exists idx_household_invites_expires
    on public.household_invites (expires_at);

-- ============================================================================
-- RLS helper functions
--
-- SECURITY DEFINER so they bypass RLS when checking membership -- otherwise
-- a policy that queries household_members would recurse into its own RLS
-- and either error or silently fail. auth.uid() is Supabase-provided and
-- reads the JWT 'sub' claim.
-- ============================================================================
create or replace function public.user_household_ids()
returns setof uuid
language sql
stable
security definer
set search_path = public
as $$
    select household_id
    from household_members
    where user_id = auth.uid()
$$;

create or replace function public.is_member_of(target_household uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from household_members
        where user_id = auth.uid()
          and household_id = target_household
    )
$$;

create or replace function public.is_household_owner(target_household uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from household_members
        where user_id = auth.uid()
          and household_id = target_household
          and role = 'owner'
    )
$$;

grant execute on function public.user_household_ids()            to authenticated;
grant execute on function public.is_member_of(uuid)              to authenticated;
grant execute on function public.is_household_owner(uuid)        to authenticated;
